### ISSUE TITLE
Warning on CI

### ISSUE THREAD

**Issue by l3nz** [martinklepsch/cljdoc#51]
While it appears to work correctly, there is a bad looking warning on the CI log: es https://circleci.com/gh/martinklepsch/cljdoc-builder/291

```
Your config file has errors and may not run correctly:
jobs: build: docker: 0: extraneous key [cmd] is not permitted

```
Looks like a typo somewhere?

**Comment by martinklepsch** [comment]
It was [the recommended way](https://discuss.circleci.com/t/builds-getting-killed-with-vague-message-received-signal-killed/10214/12) at some point but it seems `cmd` got renamed to `command`. Fixed here: https://github.com/martinklepsch/cljdoc-builder/commit/a72b1fda447c9bc97fdb90d7870e46bec24a2cd7

Thanks for raising this. It didn't really bother me because I knew stuff still worked but new users might rightfully get confused/think something is broken.
