### ISSUE TITLE
Escape HTML in docstrings

### ISSUE THREAD

**Issue by plexus** [martinklepsch/cljdoc#71]
HTML tags and special characters are rendered literally, which can quite easily lead to broken markup.

Example:

``` clojure
(defn color-8-bit
  "Parse a \"8-bit\" color, given the code that follows on ESC[38;5;<code>m."
  [code]
  ,,,)
```

https://cljdoc.xyz/d/lambdaisland/ansi/0.1.2/api/lambdaisland.ansi#color-8-bit

**Comment by martinklepsch** [comment]
Thanks for reporting this! Noticed it before but didn’t get to it yet. 

Since we’re processing stuff as markdown I guess we will need to look into escaping the HTML before it gets processed by the Markdown renderer (otherwise it will be indistinguishable from HTML resulting from the Markdown conversion.)

**Comment by plexus** [comment]
In that case this should be the responsibility of your markdown parser. A good parser will allow you to configure whether you allow mixing HTML and markdown or not.

**Comment by martinklepsch** [comment]
Fixed, see here: https://cljdoc.xyz/d/lambdaisland/ansi/0.1.2/api/lambdaisland.ansi#color-8-bit
