### ISSUE TITLE
License this under MPL v2.0?

### ISSUE THREAD

**Issue by martinklepsch** [martinklepsch/cljdoc#8]
I'm considering licensing the code in this repository under the Mozilla Public License v2.0.

Some good (and side-taking) outline of how it differs from BSD and GPL style licenses can be found in this blog post: [Why You Should Choose MPL v2 For Your OpenSource Project](http://veldstra.org/2016/12/09/you-should-choose-mpl2-for-your-opensource-project.html).

If you have opinions on this, now is a good time to make them heard.

**Comment by danielcompton** [comment]
If you ever want to do anything with rewriting Clojure's docstrings then they need to be licensed EPL, but other than that MPL 2.0 seems fine, although I'm not sure how it differs from EPL, they both seem to be non-viral copyleft licenses.

**Comment by arrdem** [comment]
I don't see a reason to deviate from the EPL. The MPL seems to provide a weaker form of copyleft than the EPL, but I don't particularly see that as an advantage since the EPL already allows embedding within non-free applications and the MLP seems just be more generous in terms of what it considers the boundary of a derivative work.

Moreover, I don't think it's useful to make people who're looking at expanding upon this work stop and think about the license. Licenses are scary especially for businesses and there's a strong consensus at present in the Clojure community that the EPL is acceptable, baring the people who insist on trying to apply the GPLs.
